// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to generate email subjects for payment reminders, tailoring the subject based on the payment due date proximity.
 *
 * - generateEmailSubject - A function that generates an email subject.
 * - GenerateEmailSubjectInput - The input type for the generateEmailSubject function.
 * - GenerateEmailSubjectOutput - The return type for the generateEmailSubject function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEmailSubjectInputSchema = z.object({
  daysUntilDue: z.number().describe('The number of days until the payment is due.'),
  clientName: z.string().describe('The name of the client.'),
  paymentAmount: z.number().describe('The amount due.'),
});
export type GenerateEmailSubjectInput = z.infer<typeof GenerateEmailSubjectInputSchema>;

const GenerateEmailSubjectOutputSchema = z.object({
  subject: z.string().describe('The generated email subject.'),
});
export type GenerateEmailSubjectOutput = z.infer<typeof GenerateEmailSubjectOutputSchema>;

export async function generateEmailSubject(input: GenerateEmailSubjectInput): Promise<GenerateEmailSubjectOutput> {
  return generateEmailSubjectFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEmailSubjectPrompt',
  input: {schema: GenerateEmailSubjectInputSchema},
  output: {schema: GenerateEmailSubjectOutputSchema},
  prompt: `You are an AI email subject line generator specializing in crafting effective payment reminder emails.

  Based on the number of days until the payment is due, generate an appropriate email subject line to increase open rates. The subject line should be concise, clear, and professional.

  Here are some guidelines:
  - If the payment is due in 1-3 days, create a sense of urgency.
  - If the payment is due in 4-7 days, be informative and proactive.
  - If the payment is due in more than 7 days, be gentle and friendly.

  Client Name: {{{clientName}}}
  Payment Amount: {{{paymentAmount}}}
  Days Until Due: {{{daysUntilDue}}}

  Subject:`,
});

const generateEmailSubjectFlow = ai.defineFlow(
  {
    name: 'generateEmailSubjectFlow',
    inputSchema: GenerateEmailSubjectInputSchema,
    outputSchema: GenerateEmailSubjectOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
